sudo: required
services:
  - docker

before_install:
  - docker build -t jpstanway/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jpstanway/react-test npm test

after_success:
  - docker build -t jpstanway/multi-client ./client
  - docker build -t jpstanway/multi-nginx ./nginx
  - docker build -t jpstanway/multi-server ./server
  - docker build -t jpstanway/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push jpstanway/multi-client
  - docker push jpstanway/multi-nginx
  - docker push jpstanway/multi-server
  - docker push jpstanway/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-268879124235
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
